# Generated by Django 2.1 on 2018-11-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippetTest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadUser', models.TextField()),
                ('editedBy', models.TextField()),
                ('originalSnippet', models.TextField()),
                ('editedSnippet', models.TextField()),
            ],
        ),
    ]
